// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTcCUD_4BXjy42ENfBboybRI12hIth_Yk',
    appId: '1:171160385453:web:bbb7a539421dddf6631324',
    messagingSenderId: '171160385453',
    projectId: 'proyectoigmar',
    authDomain: 'proyectoigmar.firebaseapp.com',
    storageBucket: 'proyectoigmar.firebasestorage.app',
    measurementId: 'G-7Q2M898S4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3M4VI9Hw48eHfT2WoUi9hYq0Zucsk9kM',
    appId: '1:171160385453:android:b3aca3655c75d38e631324',
    messagingSenderId: '171160385453',
    projectId: 'proyectoigmar',
    storageBucket: 'proyectoigmar.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTcCUD_4BXjy42ENfBboybRI12hIth_Yk',
    appId: '1:171160385453:web:f6406638587a8e37631324',
    messagingSenderId: '171160385453',
    projectId: 'proyectoigmar',
    authDomain: 'proyectoigmar.firebaseapp.com',
    storageBucket: 'proyectoigmar.firebasestorage.app',
    measurementId: 'G-JCJK61TM91',
  );
}
